version: '3'
services:
  neo4j:
    image: neo4j:4.3.6
    hostname: neo4j
    container_name: neo4j
    healthcheck:
      test: ["CMD", "sh", "-c", "echo :exit | cypher-shell"]
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/var/lib/neo4j/import/data
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_allow__upgrade: "true"
  cost-calculator:
    image: flixbus/cost-calculator:latest
    depends_on:
      neo4j:
        condition: service_healthy
      import-job:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      SPRING_NEO4J_URI: bolt://neo4j:7687
  import-job:
    image: neo4j:4.3.6
    volumes:
      - ./load_data.cypher:/var/lib/neo4j/import/load_data.cypher
    depends_on:
      neo4j:
        condition: service_healthy
    entrypoint:
      ["cypher-shell", "-a", "bolt://neo4j:7687", "-f","/var/lib/neo4j/import/load_data.cypher", "--debug"]
