spring:
  neo4j:
    uri: bolt://localhost:7687


management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: [health, info, prometheus]
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 9090
